import sqlite3
conn = sqlite3.connect('clubtech.db')
cur = conn.cursor()

# Delete test members generated by test_api.py
test_ids = cur.execute(
    "SELECT id FROM members WHERE email LIKE '%test%' OR email LIKE 'karim.tazi%'"
).fetchall()
test_ids = [r[0] for r in test_ids]
print('Deleting test member IDs:', test_ids)
for tid in test_ids:
    cur.execute("DELETE FROM attendances WHERE member_id=?", (tid,))
    cur.execute("DELETE FROM members WHERE id=?", (tid,))
conn.commit()

# Verify
remaining = cur.execute("SELECT id, member_number, first_name, last_name, is_bureau FROM members ORDER BY id").fetchall()
print("Remaining members:")
for m in remaining:
    print(f"  ID={m[0]}, Num={m[1]}, {m[2]} {m[3]}, Bureau={m[4]}")

# Prune orphaned logs and discussion messages
cur.execute("DELETE FROM action_logs WHERE id NOT IN (SELECT id FROM action_logs ORDER BY id DESC LIMIT 50)")
conn.commit()
print("\nDatabase cleaned successfully.")
conn.close()
